#!/usr/bin/env bash
set -o pipefail
generate-test-checks.py --starts_from_scope=0 "$@" \
    | perl -pe 's/^(.*)\/\// */' \
    | perl -ne 'print if $i++ > 6' \
    | perl -pe 'BEGIN{print "(*";}END{print " *)\n"}'
