(* Auto-generated by genchecks.py *)
(*
RUN: p3 --freestanding --dump-types %s | FileCheck %s
CHECK: val: t1 : (λ unit unit)
CHECK: val: t2 : (λ string unit)
CHECK: val: t3 : (λ '[[T1:.+]] unit)
CHECK: val: map : (λ (λ '[[T1:.+]] '[[T2:.+]]) (list '[[T1]]) (list '[[T2]]))
CHECK: val: get : (λ '[[T1:.+]] int '[[T1]])
CHECK: val: ( ^ ) : (λ string string string)
CHECK: val: t4 : (λ (array '[[T1:.+]]) '[[T1]])
CHECK: val: t5 : (λ (array int) int)
CHECK: val: t6 : (λ (array int) int)
CHECK: val: t7 : (λ (option '[[T1:.+]]) '[[T1]])
CHECK: val: t8 : (λ (option int) float)
CHECK: val: t9 : (λ (option int) (option int))
*)
type 'a array
val t1 : unit -> unit
val t2 : string -> unit
val t3 : 'a -> unit
val map : ('a -> 'b) -> 'a list -> 'b list
external get : 'a -> int -> 'a = "%array_safe_get"
val ( ^ ) : string -> string -> string
type 'a arrayalias = 'a array
val t4 : 'a arrayalias -> 'a
val t5 : int arrayalias -> int
type iarray = int array
val t6 : iarray -> int
type 'a t = 'a option = None | Some of 'a
val t7 : 'a t -> 'a
val t8 : int t -> float
type t2 = int t
val t9 : t2 -> int option
