#!/usr/bin/env perl
use warnings;
use strict;

# Get the path to the current script
use FindBin qw($RealBin);
use File::Temp qw/ tempfile tempdir /;

my $realbin = $RealBin;

my $arg = shift;

my $compiler = "$realbin/ocamlc2-tomlir2";
my $mlirtranslate = `which mlir-translate`;
chomp($mlirtranslate);
my $linker = "$realbin/ocamlc2-link";

die "Input file not provided" unless $arg and -f $arg;
my $basename = `basename $arg`;
chomp($basename);
my $tempdir = tempdir(CLEANUP => 1);
my $mlir_file = "$tempdir/$basename.mlir";
my $llvmir_file = "$tempdir/$basename.ll";
my $output_file = "./a.out";

sub orDie {
  my $cmd = shift;
  my $msg = shift;
  print "+ $cmd\n";
  system($cmd) == 0 or die "Failed to run $msg: $!";
}

orDie("$compiler $arg > $mlir_file", "compile $arg to MLIR");
orDie("$mlirtranslate --mlir-to-llvmir $mlir_file > $llvmir_file", "translate MLIR to LLVM IR");
orDie("$linker $llvmir_file -o $output_file", "link LLVM IR to executable");
